# Generated by Django 4.0.4 on 2022-06-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCoderSpace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='imagen',
            field=models.ImageField(default='https://eitrawmaterials.eu/wp-content/uploads/2016/09/person-icon.png', upload_to=''),
            preserve_default=False,
        ),
    ]
