# Generated by Django 4.0.4 on 2022-06-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCoderSpace', '0003_alter_blogmodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='imagen',
            field=models.URLField(max_length=300),
        ),
    ]
